### ISSUE TITLE
[Question]: Get alignment transformation

### ISSUE THREAD

**Issue by akryeem** [BGU-CS-VIL/dtan#11]
Hi @ronshapiraweber 
We are using DTAN in one of our academic projects to align some time-series data, and we are wondering what is the right way to get the alignment transformation. By "alignment transformation" I mean the transformation that can be applied (after training) on a given misaligned signal and get the aligned signal as output.

So far I thought this could be the [theta ](https://github.com/BGU-CS-VIL/dtan/blob/master/DTAN/DTAN_layer.py#L85) from [stn function](https://github.com/BGU-CS-VIL/dtan/blob/master/DTAN/DTAN_layer.py#L82).
Based on some experiments I did so far, it doesn't seem to be the right transformation. 
Do you have any suggestions or ideas on what is the most efficient and accurate way to get such a transformation after training phase completes?

Thanks,
Alaa

**Comment by ronshapiraweber** [comment]
Hi @akryeem ,
To transform test data after training, simply call `X_trasformed = model(X)`. This will predict theta and apply it to the input, X.

Theta is indeed the transformation parameter. The transformation itself is obtained by the cpab class instance, which could be reached by
`model.T.transform_data(x, theta, outsize=(self.input_shape,))`

You can call the model with some data and "return_theta" flag to get both the transformed data and theta. 
I.e., 
`transformed_input_tensor, thetas = model(X, return_theta=True)`
As can be seen [here](https://github.com/BGU-CS-VIL/dtan/blob/06637abee88e8255f2cc9afbb0f8072429426399/helper/plotting_torch.py#L135), for instance.

I'm not sure why wasn't your 'theta' the correct transformation. One thing which comes to mind is the use of RDTAN and then calling `T.transform_data(...)` directly. Note that it should be called for each recurrent. The easier way would be calling `model(x)`.

Please let me know if there's anything else. 

Cheers,
Ron

**Comment by akryeem** [comment]
Thanks for the quick reply Ron!
I'll try these out and update.

**Comment by ronshapiraweber** [comment]
Hi @akryeem , 
Please let me know how it goes and if I can close this issue.

Cheers, 
Ron

**Comment by akryeem** [comment]
I was able to make it work at the end :) (it wasn't straightforward w.r.t the preprocessing needed in the input signal).
I will close this issue
