### ISSUE TITLE
DTAN training on personal time series. tensorflow.python.framework.errors_impl.InvalidArgumentError: unique expects a 1D vector.

### ISSUE THREAD

**Issue by gauravkuppa** [BGU-CS-VIL/dtan#2]
I am trying to run the alignment network on my own dataset. 

I modified UCR_alignment and use a X_train and y_train that have the dimensions (num_samples, time_series_length, 1) and (num_samples, ) respectively. This directly mirrors all UCR archive datasets formatting.

However, I am getting the following error when I use my personal dataset vs. UCR archive dataset. What am I doing wrong? I am sure it is not an issue with the tensorflow version?

```
/home/gk32721/dtan/venv_dtan/lib/python3.6/site-packages/tensorflow/python/ops/g                          radients_impl.py:108: UserWarning: Converting sparse IndexedSlices to a dense Te                          nsor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Train on 3 samples, validate on 1 samples
Epoch 1/1000
2020-07-06 09:43:21.556262: W tensorflow/core/framework/op_kernel.cc:1273] OP_RE                          QUIRES failed at transpose_op.cc:157 : Invalid argument: transpose expects a vec                          tor of size 1. But input(1) is a vector of size 2
Traceback (most recent call last):
  File "../examples/UCR_alignment.py", line 105, in <module>
    run_UCR_alignment(args, dataset_name="Computers")
  File "../examples/UCR_alignment.py", line 81, in run_UCR_alignment
    model, DTAN = run_alignment_network(X_train, y_train, args)
  File "/home/gk32721/dtan/models/train_model.py", line 62, in run_alignment_net                          work
    verbose=1)
  File "/home/gk32721/dtan/venv_dtan/lib/python3.6/site-packages/tensorflow/pyth                          on/keras/engine/training.py", line 1605, in fit
    validation_steps=validation_steps)
  File "/home/gk32721/dtan/venv_dtan/lib/python3.6/site-packages/tensorflow/pyth                          on/keras/engine/training_arrays.py", line 232, in fit_loop
    verbose=0)
  File "/home/gk32721/dtan/venv_dtan/lib/python3.6/site-packages/tensorflow/pyth                          on/keras/engine/training_arrays.py", line 436, in test_loop
    batch_outs = f(ins_batch)
  File "/home/gk32721/dtan/venv_dtan/lib/python3.6/site-packages/tensorflow/pyth                          on/keras/backend.py", line 2978, in __call__
    run_metadata=self.run_metadata)
  File "/home/gk32721/dtan/venv_dtan/lib/python3.6/site-packages/tensorflow/pyth                          on/client/session.py", line 1399, in __call__
    run_metadata_ptr)
  File "/home/gk32721/dtan/venv_dtan/lib/python3.6/site-packages/tensorflow/pyth                          on/framework/errors_impl.py", line 526, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: unique expects a 1D vector.
         [[{{node loss/Temporal_Alignment_Layer0_loss/Unique}} = Unique[T=DT_FLO                          AT, _class=["loc:@loss/...yScatterV3"], out_idx=DT_INT32, _device="/job:localhos                          t/replica:0/task:0/device:CPU:0"](loss/Temporal_Alignment_Layer0_loss/Squeeze)]]
```

**Comment by ronshapiraweber** [comment]
Hi Gaurav, 

The error seems to be related to the computation of the alignment loss. 
1. Are you using 1-hot encoded labels or numeric one? UCR uses numeric ones (or at least used to) and this is how the code expects them to be. 
2. For you code snip - "Train on 3 samples, validate on 1 samples", recall that the loss is computed within class. Since you are using 4 samples, it might be due to empty class during validation (or something to this sort). Does this occur for a larger sample size? 

Hope this helps, let me know if you need anything else. 

Cheers

**Comment by gauravkuppa** [comment]
Thanks for the response. I am using a label of 1 for each time-series, because I want to use the unsupervised-learning approach for joint-alignment. According to the paper, a single class label leads to unsupervised learning approach.

I do only use 4 samples, because I wanted to test the network on a subset of data. None of the data has an empty class, just a single class.

Is it all right to use a single class? Otherwise, how do I use the unsupervised learning approach as mentioned in the paper?

Thanks

**Comment by ronshapiraweber** [comment]
No problems! 

There shouldn't be a problem using a single class, perhaps tf.unique() doesn't work well with scalars...
I would:
1. Check that the dims of you labels array match the UCR ones. 

2. `l2_alignment_loss(self, X_within_class) `from `def loss_func(y_true, y_pred)` inside dtan/alignment_loss.py instead of the within-class loss. 

I would try to take a look once I have access to my machine if it still does not resolve.

**Comment by ronshapiraweber** [comment]
Works for me with a single class. My bet is on the data dim of the lables vector:
labels dim.shape = (n_samples, )

Please let me know if this resolves your issue.

**Comment by gauravkuppa** [comment]
Unfortunately, it does not. I can show you that the dimensions for the labels are (n_samples, ).

<img width="658" alt="ucr_loader_influx" src="https://user-images.githubusercontent.com/24405632/87065643-2b28c900-c1c6-11ea-8c1c-7c5be80bbd26.png">

The influx_dataloader is my person dataloader and the UCR_loader is the loader you all provide. Essentially, the output is printing out these statements

``` python
X_train, y_train = data_loader.load()
print(X_train.shape, y_train.shape)
print(np.unique(X_train), np.unique(y_train))
```

As you can see, X_train.shape is (n_samples, seq_length, 1) and y_train.shape is (n_samples, )

I am not sure if I am missing something here

**Comment by ronshapiraweber** [comment]
OK I was able to reproduce it. 
It might come down to changing the label to 0 (as oppose to 1). 

Something with TensorFlow's Unique() function, super annoying. 

Hope this works.

**Comment by gauravkuppa** [comment]
I changed the single-class label to 0, from 1. That did not make a difference. I am receiving the same tf.unique() error.

Was there any other thing that could fix it?

**Comment by ronshapiraweber** [comment]
I'm not sure at this point. 
Since I was able to reproduce the error by transforming the label from 1 to 0, I still suspect it somewhat related. 

Does the model works with your data, given several classes (For instance, labels in [0 ,1] )?

**Comment by ronshapiraweber** [comment]
Hi gaurav,
I think the problem stems from the fact the validation set size = 1. 
Would you mind reproducing it on your end with validation set size > 1? 

Thanks

**Comment by ronshapiraweber** [comment]
Hi gaurav, 
Please let me know If I can close this issue.

Cheers

**Comment by gauravkuppa** [comment]
Yes you can close this. Thank you for your help!
