### ISSUE TITLE
mode.save() not working

### ISSUE THREAD

**Issue by gauravkuppa** [BGU-CS-VIL/dtan#3]
I know you all have said that you are aware of this problem, and plan to fix it in an upcoming release.

However, I am under a time crunch and cannot wait for the new release to save my trained model. Is there a workaround in TF 1.11 that you are aware of currently?

**Comment by ronshapiraweber** [comment]
I'm sorry to hear that you're under a tight schedule and that this bug might be a bottle neck. 

Unfortunately, we did not find any fix in TF 1.11-1.14. 
Upgrading to TF2.0 also raised various issues, therefor, we are currently working on a PyTorch implementation. 

A somewhat 'bad' solution that might help is saving the aligned data after conducting your experiments and then analyzing it offline (though it might not be relevant to your setting).

**Comment by gauravkuppa** [comment]
Okay, sure. What is the timeline for this PyTorch implementation? 

Are there any other workarounds to save the models? I wanted to do some transfer learning on your model.

**Comment by ronshapiraweber** [comment]
Model saving is now fixed in the new PyTorch branch (!)
Please check it out and let me know if I can close this issue.

**Comment by gauravkuppa** [comment]
Sure, I am checking out the PyTorch branch now

**Comment by gauravkuppa** [comment]
I am getting a ImportError: from libcpab import Cpab, I will reference this in a new issue.
