### ISSUE TITLE
ImportError: from libcpab import Cpab, Pytorch Branch

### ISSUE THREAD

**Issue by gauravkuppa** [BGU-CS-VIL/dtan#4]
I am getting a ImportError: from libcpab import Cpab, I will reference this in a new issue.

_Originally posted by @gauravkuppa in https://github.com/BGU-CS-VIL/dtan/issues/3#issuecomment-668734915_

**Comment by ronshapiraweber** [comment]
Hi Gaurav, 
As mentioned in the README for that branch, the PyTorch branch uses the up-to-date version of libcpab (v2.0). 

I suspect this is why you are getting ImportError.
I suggest updating and running one of their examples (verify the library works).
